<a href="https://colab.research.google.com/github/manaswini191/internproject/blob/main/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Code Clause PVT LTD

Project1: Credit Card Fraud Detection

Name:M.Manaswini

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#loading the dataset to pandas dataframe
creditcard_data = pd.read_csv('/content/creditcard.csv')

In [3]:
#first 5 rows of the dataset
creditcard_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
#last 5 rows
creditcard_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
109020,71183,-4.374232,4.597323,-2.666504,-0.495896,-0.335102,1.979937,-5.900575,-11.761583,-2.595467,...,-6.200810,1.783418,0.631746,-1.187762,-0.086872,0.155966,-0.524525,0.190889,0.76,0.0
109021,71184,-0.764535,-0.169528,2.400210,-2.646822,-1.295989,-0.560579,-0.376060,-0.020719,-1.946566,...,-0.094532,0.343778,-0.302877,0.483442,0.352366,-0.219257,0.249637,-0.046422,4.80,0.0
109022,71184,-0.729627,0.652197,1.544893,-1.142110,0.013696,-0.330441,0.720784,-0.057366,0.836247,...,-0.115648,0.216192,-0.174437,0.149820,-0.233584,0.907150,0.239993,0.012831,10.00,0.0
109023,71184,1.216414,-0.913359,1.163761,-0.386409,-1.603284,-0.362882,-0.984403,-0.046064,-0.166277,...,0.172531,0.510539,-0.088030,0.447209,0.374703,-0.207254,0.048581,0.041604,78.00,0.0
109024,71184,-1.183731,0.184305,0.854433,-0.102827,1.458303,1.078913,0.173125,0.556277,-0.195907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#dataset information
creditcard_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109025 entries, 0 to 109024
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    109025 non-null  int64
 1   V1      109025 non-null  float64
 2   V2      109025 non-null  float64
 3   V3      109025 non-null  float64
 4   V4      109025 non-null  float64
 5   V5      109025 non-null  float64
 6   V6      109025 non-null  float64
 7   V7      109025 non-null  float64
 8   V8      109025 non-null  float64
 9   V9      109025 non-null  float64
 10  V10     109025 non-null  float64
 11  V11     109025 non-null  float64
 12  V12     109025 non-null  float64
 13  V13     109025 non-null  float64
 14  V14     109025 non-null  float64
 15  V15     109025 non-null  float64
 16  V16     109025 non-null  float64
 17  V17     109025 non-null  float64
 18  V18     109025 non-null  float64
 19  V19     109025 non-null  float64
 20  V20     109025 non-null  float64
 21  V21     109024 non-null  float64
 22  V22     109024 non-null  float64
 23  V23     109024 non-null  float64
 24  V24     109024 non-null  float64
 25  V25     109024 non-null  float64
 26  V26     109024 non-null  float64
 27  V27     109024 non-null  float64
 28  V28     109024 non-null  float64
 29  Amount  109024 non-null  float64
 30  Class   109024 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 25.8 MB

In [6]:
#checking the number of missing values in each column
creditcard_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
#distribution of legit transactions and fraudulent transactions
creditcard_data['Class'].value_counts()

0.0    108785
1.0       239
Name: Class, dtype: int64

This Dataset is highly unbalanced

0 --> Normal Transaction
1 --> Fraudulent Transaction

In [9]:
#separating the data for analysis
legit = creditcard_data[creditcard_data.Class == 0]
fraud = creditcard_data[creditcard_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(108785, 31)
(239, 31)

In [11]:
#statistical measures of the data
legit.Amount.describe()

count    108785.000000
mean         95.924584
std         259.993259
min           0.000000
25%           7.030000
50%          25.040000
75%          86.800000
max       19656.530000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     239.000000
mean      119.677573
std       255.678875
min         0.000000
25%         1.000000
50%         7.610000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [13]:
#compare the values for both transactions
creditcard_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,44657.767707,-0.244295,-0.034388,0.700385,0.146054,-0.275096,0.100015,-0.102167,0.055517,-0.052238,...,0.042448,-0.034487,-0.107976,-0.036938,0.010819,0.132820,0.025705,0.000529,0.001429,95.924584
1.0,38848.740586,-5.982672,4.179679,-7.675194,4.747225,-4.271010,-1.536196,-6.358147,1.600009,-2.747560,...,0.261212,1.356023,-0.341016,-0.100372,-0.112906,0.215685,0.091744,0.533488,0.067655,119.677573

Under Sampling

Build a sample dataset containing similar distribution of normal transactions and fraudulent Transactions

Number of Fraudulent Transactions --> 239

In [14]:
legit_sample = legit.sample(n=239)

Concatenating two DataFrames

In [15]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1144,892,-0.654401,1.157197,0.978790,0.804280,1.181281,0.876832,1.019566,-0.280048,0.347691,...,-0.296787,0.102785,-0.352439,-1.297371,0.191535,-0.183538,0.332333,-0.122636,13.27,0.0
19719,30497,-0.863635,0.245013,1.817200,2.115632,-1.934569,1.080894,1.733906,-0.077608,-0.040750,...,0.143303,0.734594,0.182371,0.769073,-0.016888,-0.033227,0.099324,-0.026922,397.42,0.0
100227,67457,-1.418176,-0.323437,2.609021,-1.053864,-1.304296,0.846653,-1.355373,0.651300,0.637246,...,0.208797,0.955778,-0.264638,0.042114,-0.001441,-0.059685,0.132713,0.257485,1.00,0.0
106444,69967,-1.422042,-4.635902,-1.697578,1.083478,0.064883,4.434252,0.501638,0.734588,0.404053,...,1.028462,-0.226274,-1.311180,1.083783,0.029016,-0.385108,-0.178663,0.274934,1375.00,0.0
35527,38156,0.964904,-1.287420,1.679457,1.169608,-1.870159,1.028888,-1.457852,0.480219,0.803118,...,-0.355013,-0.287806,-0.058746,0.060591,0.300960,-0.200735,0.125539,0.055203,108.86,0.0

In [17]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
106998,70229,0.315642,1.636778,-1.519650,4.028571,-1.186794,-0.789813,-2.279807,0.472988,-1.657635,...,0.345921,-0.108002,-0.165442,0.279895,0.808783,0.117363,0.589595,0.309064,3.79,1.0
107067,70270,-1.512516,1.133139,-1.601052,2.813401,-2.664503,-0.310371,-1.520895,0.852996,-1.496495,...,0.729828,0.485286,0.567005,0.323586,0.040871,0.825814,0.414482,0.267265,318.11,1.0
107637,70536,-2.271755,-0.457655,-2.589055,2.230778,-4.278983,0.388610,0.102485,0.813128,-1.092921,...,1.096342,0.658399,1.711676,0.333540,0.538591,-0.193529,0.258194,0.247269,824.83,1.0
108258,70828,0.196707,1.189757,0.704882,2.891388,0.045555,1.245730,-1.198714,-2.421616,-1.232089,...,-1.328132,0.189311,-0.005524,-0.814708,0.400924,0.286281,0.135215,0.257315,0.76,1.0
108708,71033,-3.170818,0.185735,-3.399852,3.761155,-2.148047,-1.598944,-2.519565,1.316215,-2.400106,...,1.092051,-0.041080,0.904395,0.180016,0.049970,-0.257100,0.859282,0.225924,426.40,1.0

In [18]:
new_dataset['Class'].value_counts()

0.0    239
1.0    239
Name: Class, dtype: int64

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,44980.661088,-0.396480,-0.084443,0.769322,0.177218,-0.297515,0.154176,-0.071230,0.095890,0.003277,...,0.109113,-0.050520,-0.048500,0.006011,-0.044562,0.100438,0.035631,0.010250,0.011982,117.633849
1.0,38848.740586,-5.982672,4.179679,-7.675194,4.747225,-4.271010,-1.536196,-6.358147,1.600009,-2.747560,...,0.261212,1.356023,-0.341016,-0.100372,-0.112906,0.215685,0.091744,0.533488,0.067655,119.677573

Splitting the data into Figures and Targets

In [20]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

         Time        V1        V2        V3        V4        V5        V6  \
1144      892 -0.654401  1.157197  0.978790  0.804280  1.181281  0.876832
19719   30497 -0.863635  0.245013  1.817200  2.115632 -1.934569  1.080894
100227  67457 -1.418176 -0.323437  2.609021 -1.053864 -1.304296  0.846653
106444  69967 -1.422042 -4.635902 -1.697578  1.083478  0.064883  4.434252
35527   38156  0.964904 -1.287420  1.679457  1.169608 -1.870159  1.028888
...       ...       ...       ...       ...       ...       ...       ...
106998  70229  0.315642  1.636778 -1.519650  4.028571 -1.186794 -0.789813
107067  70270 -1.512516  1.133139 -1.601052  2.813401 -2.664503 -0.310371
107637  70536 -2.271755 -0.457655 -2.589055  2.230778 -4.278983  0.388610
108258  70828  0.196707  1.189757  0.704882  2.891388  0.045555  1.245730
108708  71033 -3.170818  0.185735 -3.399852  3.761155 -2.148047 -1.598944

              V7        V8        V9  ...       V20       V21       V22  \
1144    1.019566 -0.280048  0.347691  ...  0.592322 -0.296787  0.102785
19719   1.733906 -0.077608 -0.040750  ... -0.154306  0.143303  0.734594
100227 -1.355373  0.651300  0.637246  ...  0.064233  0.208797  0.955778
106444  0.501638  0.734588  0.404053  ...  2.806149  1.028462 -0.226274
35527  -1.457852  0.480219  0.803118  ... -0.473353 -0.355013 -0.287806
...          ...       ...       ...  ...       ...       ...       ...
106998 -2.279807  0.472988 -1.657635  ...  0.388885  0.345921 -0.108002
107067 -1.520895  0.852996 -1.496495  ...  1.249586  0.729828  0.485286
107637  0.102485  0.813128 -1.092921  ...  2.285758  1.096342  0.658399
108258 -1.198714 -2.421616 -1.232089  ...  0.646616 -1.328132  0.189311
108708 -2.519565  1.316215 -2.400106  ...  1.932254  1.092051 -0.041080

             V23       V24       V25       V26       V27       V28   Amount
1144   -0.352439 -1.297371  0.191535 -0.183538  0.332333 -0.122636    13.27
19719   0.182371  0.769073 -0.016888 -0.033227  0.099324 -0.026922   397.42
100227 -0.264638  0.042114 -0.001441 -0.059685  0.132713  0.257485     1.00
106444 -1.311180  1.083783  0.029016 -0.385108 -0.178663  0.274934  1375.00
35527  -0.058746  0.060591  0.300960 -0.200735  0.125539  0.055203   108.86
...          ...       ...       ...       ...       ...       ...      ...
106998 -0.165442  0.279895  0.808783  0.117363  0.589595  0.309064     3.79
107067  0.567005  0.323586  0.040871  0.825814  0.414482  0.267265   318.11
107637  1.711676  0.333540  0.538591 -0.193529  0.258194  0.247269   824.83
108258 -0.005524 -0.814708  0.400924  0.286281  0.135215  0.257315     0.76
108708  0.904395  0.180016  0.049970 -0.257100  0.859282  0.225924   426.40

[478 rows x 30 columns]

In [22]:
print(Y)

1144      0.0
19719     0.0
100227    0.0
106444    0.0
35527     0.0
         ...
106998    1.0
107067    1.0
107637    1.0
108258    1.0
108708    1.0
Name: Class, Length: 478, dtype: float64

Split the data into Training data and Testing data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(478, 30) (382, 30) (96, 30)

Model Training

Logistic Regression

In [25]:
model = LogisticRegression()

In [26]:
#training the Logistic Regression Model with Training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [28]:
#accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [29]:
print('Accuracy on Training Data : ',training_data_accuracy)

Accuracy on Training Data :  0.9633507853403142

In [31]:
#accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [32]:
print('Accuracy score on Test Data : ',test_data_accuracy)

Accuracy score on Test Data :  0.9583333333333334